# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_commodityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_farmLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=50)),
                ('subDistrict', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('size', models.IntegerField()),
                ('soilType', models.CharField(max_length=50)),
                ('waterSystem', models.CharField(max_length=25)),
                ('purpose', models.CharField(max_length=8)),
                ('server', models.ImageField(blank=True, upload_to='ProfileImageWaliFile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_stockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sellingRate', models.IntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmer_commodityRecord')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
