# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-05 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_farmland',
            name='server',
            field=models.ImageField(blank=True, upload_to='UserProfilePics'),
        ),
    ]
