# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_farmer_commodityrecord_farmer_stockrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_stockrecord',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
