# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmer_farmland_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_farmland',
            name='server',
            field=models.TextField(),
        ),
    ]
