# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20190404_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_farmland',
            name='server',
            field=models.ImageField(blank=True, upload_to='ProfileImageWaliFile'),
        ),
    ]
