# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190404_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
