# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190404_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('1', 'Farmer'), ('2', 'Industry'), ('3', 'Logistics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('1', 'India'), ('2', 'Out of India')], max_length=40),
        ),
    ]
